### ISSUE TITLE
Copilot 

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/plugin_sublime#1]
One of the most important features of pieces is asking the Copilot.

1. Add the ability to change the model used. 
2. Ask about an asset .
3. Ask for help and explain a certain selected text.
4. Adding a comprehensive ui and consistent ui for the ask command as VS to maintain consistency 
5. Add context to the model (Assets,folder/file)

**Comment by mark-at-pieces** [comment]
Feat: [COPILOT] Ask copilot about an asset
Feat: [COPILOT] Add the ability to change the Model used in a conversation
Feat: [COPILOT] Ask for help and explain a certain selected text.
Feat: [COPILOT] Adding a comprehensive ui and consistent ui for the ask command as VS to maintain consistency
Feat: [COPILOT] Add context to the model (Assets,folder/file)
