### ISSUE TITLE
Package control doesn't list this plugin

### ISSUE THREAD

**Issue by zedtux** [pieces-app/plugin_sublime#126]
Following the installation instructions from the `README.md` file doesn't work since the only "pieces" plugin package listed is one from a bitbucket.org repository:

<img width="611" alt="Screenshot 2024-07-06 at 11 33 11" src="https://github.com/pieces-app/plugin_sublime/assets/478564/598bee2d-2c2a-4cce-8f20-4a7cc67b09ea">

What worked for me was to manually download and install it following the "pre-release" instructions.

**Comment by Bishoy-at-pieces** [comment]
You we are still working on that with the package control

**Comment by Bishoy-at-pieces** [comment]
https://github.com/wbond/package_control_channel/pull/8928
