### ISSUE TITLE
Fix `default` argument for `edit_settings`

### ISSUE THREAD

**Issue by kaste** [pieces-app/plugin_sublime#129]
https://github.com/pieces-app/plugin_sublime/blob/d293190a3b72b238856ed8dd1c6d1ead753801fa/Pieces.sublime-commands#L52-L60

From the documentation:  

```
default   (string) - An optional unicode string of the default contents if the user version of the settings file does not yet exist. Use '$0' to place the cursor.
```

E.g. https://github.com/sublimelsp/LSP/blob/293f4a4340cca5ab1ad065643e4f20d9b270b2b1/Default.sublime-commands#L2-L9

**Comment by Bishoy-at-pieces** [comment]
Thank you @kaste fix it
