### ISSUE TITLE
Feedback on the Sublime Forums 

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/plugin_sublime#161]
- [x] #164
- [x] #165
some people have their own custom way (such as 2x2 layout). Putting the conversation in a normal tab
will allow the user to decide how to handle it. It also provides better UX in my opinion (closing the conversation leaves an empty column).
- [x] #166
I suggest you take a look at GitSavvy package. It represents its UI in the view itself and can be navigated
via keyboard shortcuts. Think of ST as somehow similar to neovim.
- [x] #167
Make sure that commands are discoverable in the command palette, especially the features you want to focus on
such as the ones in the context menu items (“Save to Pieces”, “Start conver…”)
- [x] #168
I have tried saving something basic like console.log in a typescript file and it either detects it as a “note” or coffeescript
- [x] What does export material do? I tried clicking save and nothing seem to happen.
- [x] #169
I do not have custom snippets but Sublime already has hundreds of snippets already from default packages. I suggest that the
command should import all snippets (tag it with “Sublime Text”) and should just import all existing and future new snippets.
This will allow the user to utilize the natural language auto completion which is definitely a plus!
- [x] #170
- [x] #171
Think of your search feature as Sublime’s “Goto Anything”. The input-to-feedback ratio should be balanced enough for the user to really use it.

https://forum.sublimetext.com/t/pieces-for-sublime-text-on-device-ai-coding-assistant-that-boosts-developer-productivity/73544/3

**Comment by kapitanluffy** [comment]
I meant for #170 and #171 to be a single statement
