### ISSUE TITLE
Ability to launch a notification in Sublime? 

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/plugin_sublime#19]
- this is probably NC (not critical) for the MVP but should come quickly after
- can layer this in to failures w/ version logic/ or PiecesOS not installed
- also can be used to launch success notifcations "selection successfully saved to pieces", xyz

**Comment by Bishoy-at-pieces** [comment]
Yup there is a message dialog like the save prompt for example we can work on that
