### ISSUE TITLE
imported sublime snippet does not open automatically

### ISSUE THREAD

**Issue by kirollos-at-pieces** [pieces-app/plugin_sublime#216]
**Issue**: when importing a sublime snippet, it does not open it once imported

**Expected Result**: the sublime should be opened automatically so the user could know it have been imported successfully

![image](https://github.com/user-attachments/assets/8fe7fb5e-2a69-4f09-b81e-2cd67e05d9e5)

**Comment by Bishoy-at-pieces** [comment]
but it opens the snippet after importing
<img width="1224" alt="Screenshot 2024-10-13 at 10 07 01 PM" src="https://github.com/user-attachments/assets/009555de-bc6a-4825-84da-3cf18447a3e3">

**Comment by kirollos-at-pieces** [comment]
this issue is on version **1.3.22.dev1**, if this solved on version **1.3.23.dev1** so ok.
